### ISSUE TITLE
TaskCompletionSourceAdapter.TrySetCanceled() Throws NullReferenceException

### ISSUE THREAD

**Issue by DorianGreen** [Particular/NServiceBus.Callbacks#53]
I am using Callbacks on an IIS hosted WebApi.

Under some circumstances, the CancellationToken callback on UpdateRequestResponseCorrelationTableBehavior is throwing a NullReferenceException when attempting to cancel the adapter.

As this exception occurs on a Task outside the scope of a HTTP request, the entire AppPool crashes.

The only clue I can provide is that I link the WebApi CancellationToken with a timeout token and pass that to IMessageSession.Request

**Comment by danielmarbach** [comment]
@DorianGreen would it be possible for you to provide a simple gist where you show how you link the two tokens?

**Comment by DorianGreen** [comment]
Here is how I link and cancel the token:
https://gist.github.com/DorianGreen/5f1ffd005eced70cc401516952251b8a

In addition to this, I register an empty message handler in case the web request timed out or got canceled by the user.

I register this empty handler to not get the "No Handlers Found..." error in my logs

**Comment by danielmarbach** [comment]
I was trying to somehow repro it but I couldn't. I even tried to nullify the linked token source and GC.Collect. I will do further investigations. Would it be possible to send in the full stack trace or a memory dump when this happens?

```
public class When_using_callback_with_linked_source : NServiceBusAcceptanceTest
    {
        [Test]
        public async Task ShouldNot_trigger_the_callback_when_canceled()
        {
            OperationCanceledException exception = null;

            var context = await Scenario.Define<Context>()
                .WithEndpoint<Replier>()
                .WithEndpoint<EndpointWithLocalCallback>(b => b.When(async (bus, ctx) =>
                {
                    var cs = new CancellationTokenSource();
                    ctx.TokenSource = cs;

                    var options = new SendOptions();

                    try
                    {
                        var cancellationToken = cs.Token;
                        var newToken = TimeoutAfter(cancellationToken, TimeSpan.FromSeconds(2));
                        GC.Collect();

                        ctx.Response = await bus.Request<MyResponse>(new MyRequest(), options, newToken);
                        ctx.CallbackFired = true;
                    }
                    catch (OperationCanceledException e)
                    {
                        exception = e;
                    }
                }))
                .Done(c => exception != null)
                .Run();

            Assert.IsNull(context.Response);
            Assert.False(context.CallbackFired);
            Assert.True(context.HandlerGotTheRequest);
            Assert.IsInstanceOf<OperationCanceledException>(exception);
        }

        static CancellationToken TimeoutAfter(CancellationToken userCt, TimeSpan timespan)
        {
            var combinedCt = CancellationTokenSource.CreateLinkedTokenSource(userCt);
            combinedCt.CancelAfter(timespan);
            Task.Run(() =>
            {
                combinedCt = null;
                GC.Collect();
            });
            return combinedCt.Token;
        }


        class Context : ScenarioContext
        {
            public CancellationTokenSource TokenSource { get; set; }

            public bool HandlerGotTheRequest { get; set; }

            public bool CallbackFired { get; set; }

            public MyResponse Response { get; set; }
        }

        class Replier : EndpointConfigurationBuilder
        {
            public Replier()
            {
                EndpointSetup<DefaultServer>(c =>
                    c.MakeInstanceUniquelyAddressable("1"));
            }

            public class MyRequestHandler : IHandleMessages<MyRequest>
            {
                public Context Context { get; set; }

                public async Task Handle(MyRequest message, IMessageHandlerContext context)
                {
                    Context.HandlerGotTheRequest = true;
                    await Task.Delay(5000);

                    await context.Reply(new MyResponse());
                }
            }
        }

        class EndpointWithLocalCallback : EndpointConfigurationBuilder
        {
            public EndpointWithLocalCallback()
            {
                EndpointSetup<DefaultServer>(c =>
                        c.MakeInstanceUniquelyAddressable("1"))
                    .AddMapping<MyRequest>(typeof(Replier));
            }
        }

        public class MyRequest : IMessage
        {
        }

        public class MyResponse : IMessage
        {
        }

    }
```

**Comment by DorianGreen** [comment]
This is the exception I get from Windows event viewer.

```
Exception: System.AggregateException

Message: One or more errors occurred.

StackTrace:    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallbackLogic(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

InnerException: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at NServiceBus.TaskCompletionSourceAdapter.TrySetCanceled()
   at NServiceBus.UpdateRequestResponseCorrelationTableBehavior.<>c.<Invoke>b__1_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
```

I cannot reproduce the issue while debugging my code.

**Comment by danielmarbach** [comment]
I was able to reproduce the issue.

The problem is the following:

The TaskCompletionSourceAdapter calls into TaskCompletionSource<TResult>.TrySetCanceled(CancelationToken token). This API is only available on .[NET 4.6 and higher](https://apisof.net/catalog/System.Threading.Tasks.TaskCompletionSource%3CTResult%3E.TrySetCanceled(CancellationToken)). Although we compile against 4.5.1 we've never found that bug because all our machines have at least 4.6 installed which will make the reflection code automatically work :( I will release a hotfix. Sorry for this inconvenience!

**Comment by danielmarbach** [comment]
Replaced by https://github.com/Particular/NServiceBus.Callbacks/issues/54

Thanks @DorianGreen for raising this.

**Comment by DorianGreen** [comment]
That would explain why I wasn't able to reproduce it on my machine.
Thanks.

**Comment by danielmarbach** [comment]
@DorianGreen we release 1.0.1 and 1.1.1. More details see https://groups.google.com/forum/#!topic/particularsoftware/eKx3jSm6hHQ
